### PR TITLE
Fix errors and warnings with byte-compilation

### PR DESCRIPTION
**Pull request by jhpalmieri**
Let's try this.

### CODE REVIEW

**Review by jdchristensen — APPROVED** [review]
I don't understand the changes to light.el, but this builds for me.  (Just two minor warnings.)

**Comment by jhpalmieri** [comment]
The changes in `light.el` amount to this: the relevant functions are supposed to be the usual Emacs functions but calling `lc-choose-completion-string` instead of `choose-completion-string`, so I copied the new versions of the Emacs functions, replacing the outdated ones in the code.

Thanks for the review. I am going to use this for a while, to see if I can trip over any new bugs that I may have introduced.

**Comment by jdchristensen** [comment]
BTW, this approach won't fix the case where someone has installed auctex manually in a directory that they add to their load-path.  The `eval` approach simply avoids evaluating the files at compile time.  The only reason emacs evaluates files that are `require`d is in case they contain macros that are needed.

**Comment by jdchristensen** [comment]
Re: changes to light.el:  What's confusing me is that there were two functions before and there is only one now.  The missing one, `lc-mouse-choose-completion`, is still bound to `mouse-2`.

About copying and editing:  I wonder if you can locally rebind `choose-completion-string` to `lc-choose-completion-string` and just call the original functions?  Or use use "advice" to achieve this?  Not sure.

**Comment by jhpalmieri** [comment]
I don't know how to use advice, but at a quick glance it doesn't seem like it will work, and it may not be a recommended procedure.

**Comment by jdchristensen** [comment]
Copying code also seems pretty fragile, as it might not work with other emacs versions.  But I quickly tested this with emacs git, and it worked.  (I don't actually use light much, so I didn't test it thoroughly.)

**Comment by jhpalmieri** [comment]
Sorry, this is broken: inserting a completion from a buffer by clicking with the mouse doesn't work with ultra-tex. (It works to open a file, but not to insert a TeX command in a buffer.) I'll fix it later.

**Comment by jhpalmieri** [comment]
> BTW, this approach won't fix the case where someone has installed auctex manually in a directory that they add to their load-path. The `eval` approach simply avoids evaluating the files at compile time. The only reason emacs evaluates files that are `require`d is in case they contain macros that are needed.

I don't mind if people have to install auctex the recommended way.

**Comment by jhpalmieri** [comment]
> Copying code also seems pretty fragile, as it might not work with other emacs versions. But I quickly tested this with emacs git, and it worked. (I don't actually use light much, so I didn't test it thoroughly.)

This is how it's been done for years, so while it is fragile in theory, in practice it has been pretty robust.

**Pull request merged**
